src/Entity/Recette.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\RecetteRepository;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


/**
 * Recette
 * @ORM\Entity(repositoryClass="App\Repository\RecetteRepository", repositoryClass=RecetteRepository::class)
 * @ORM\Table(name="recette", indexes={@ORM\Index(name="cat_id", columns={"cat_id"}), @ORM\Index(name="membre_id", columns={"auteur"}), @ORM\Index(name="theme_id", columns={"theme_id"})})
 * @Vich\Uploadable()
 */

class Recette
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var File
     * @Vich\UploadableField(mapping="recette_image", fileNameProperty="photo")
     */
    private $image_file;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=150, nullable=false)
     */
    private $nom;

    /**
     * @var bool|null
     *
     * @ORM\Column(name="active", type="boolean", nullable=true, options={"default"="1"})
     */
    private $active = true;

    /**
     * @var string
     *
     * @ORM\Column(name="descr", type="text", length=65535, nullable=false)
     */
    private $descr;

    /**
     * @var string|null
     * @ORM\Column(name="photo", type="string", length=255, nullable=true)
     */
    private $photo;

    /**
     * @var int|null
     *
     * @ORM\Column(name="rating_P", type="integer", nullable=true)
     */
    private $ratingP;

    /**
     * @var int|null
     *
     * @ORM\Column(name="rating_N", type="integer", nullable=true)
     */
    private $ratingN;

    /**
     * @var int
     *
     * @ORM\Column(name="tps_prep", type="integer", nullable=false)
     */
    private $tpsPrep;

    /**
     * @var int|null
     *
     * @ORM\Column(name="tps_cuisson", type="integer", nullable=true)
     */
    private $tpsCuisson;

    /**
     * @var int
     *
     * @ORM\Column(name="portion", type="integer", nullable=false)
     */
    private $portion;

    /**
     * @var int
     *
     * @ORM\Column(name="difficulte", type="integer", nullable=false)
     */
    private $difficulte;

    /**
     * @var \Membre
     *
     * @ORM\ManyToOne(targetEntity="Membre")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="auteur", referencedColumnName="id")
     * })
     */
    private $auteur;

    /**
     * @var \Theme
     *
     * @ORM\ManyToOne(targetEntity="Theme")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="theme_id", referencedColumnName="id")
     * })
     */
    private $theme;

    /**
     * @var \Categorie
     *
     * @ORM\ManyToOne(targetEntity="Categorie")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="cat_id", referencedColumnName="id")
     * })
     */
    private $cat;

    /**
     * @var \Doctrine\Common\Collections\Collection
     *
     * @ORM\ManyToMany(targetEntity="Membre", inversedBy="recette")
     * @ORM\JoinTable(name="favorite",
     *   joinColumns={
     *     @ORM\JoinColumn(name="recette_id", referencedColumnName="id")
     *   },
     *   inverseJoinColumns={
     *     @ORM\JoinColumn(name="membre_id", referencedColumnName="id")
     *   }
     * )
     */
    private $membre;

    /**
     * @var \Doctrine\Common\Collections\Collection
     *
     * @ORM\ManyToMany(targetEntity="Produit", mappedBy="recette")
     */
    private $produit;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->membre = new \Doctrine\Common\Collections\ArrayCollection();
        $this->produit = new \Doctrine\Common\Collections\ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(?bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getDescr(): ?string
    {
        return $this->descr;
    }

    public function setDescr(string $descr): self
    {
        $this->descr = $descr;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getRatingP(): ?int
    {
        return $this->ratingP;
    }

    public function setRatingP(?int $ratingP): self
    {
        $this->ratingP = $ratingP;

        return $this;
    }

    public function getRatingN(): ?int
    {
        return $this->ratingN;
    }

    public function setRatingN(?int $ratingN): self
    {
        $this->ratingN = $ratingN;

        return $this;
    }

    public function getTpsPrep(): ?int
    {
        return $this->tpsPrep;
    }

    public function setTpsPrep(int $tpsPrep): self
    {
        $this->tpsPrep = $tpsPrep;

        return $this;
    }

    public function getTpsCuisson(): ?int
    {
        return $this->tpsCuisson;
    }

    public function setTpsCuisson(?int $tpsCuisson): self
    {
        $this->tpsCuisson = $tpsCuisson;

        return $this;
    }

    public function getPortion(): ?int
    {
        return $this->portion;
    }

    public function setPortion(int $portion): self
    {
        $this->portion = $portion;

        return $this;
    }

    public function getDifficulte(): ?int
    {
        return $this->difficulte;
    }

    public function setDifficulte(int $difficulte): self
    {
        $this->difficulte = $difficulte;

        return $this;
    }

    public function getAuteur(): ?Membre
    {
        return $this->auteur;
    }

    public function setAuteur(?Membre $auteur): self
    {
        $this->auteur = $auteur;

        return $this;
    }

    public function getTheme(): ?Theme
    {
        return $this->theme;
    }

    public function setTheme(?Theme $theme): self
    {
        $this->theme = $theme;

        return $this;
    }

    public function getCat(): ?Categorie
    {
        return $this->cat;
    }

    public function setCat(?Categorie $cat): self
    {
        $this->cat = $cat;

        return $this;
    }

    /**
     * @return Collection|Membre[]
     */
    public function getMembre(): Collection
    {
        return $this->membre;
    }

    public function addMembre(Membre $membre): self
    {
        if (!$this->membre->contains($membre)) {
            $this->membre[] = $membre;
        }

        return $this;
    }

    public function removeMembre(Membre $membre): self
    {
        $this->membre->removeElement($membre);

        return $this;
    }

    /**
     * @return Collection|Produit[]
     */
    public function getProduit(): Collection
    {
        return $this->produit;
    }

    public function addProduit(Produit $produit): self
    {
        if (!$this->produit->contains($produit)) {
            $this->produit[] = $produit;
            $produit->addRecette($this);
        }

        return $this;
    }

    public function removeProduit(Produit $produit): self
    {
        if ($this->produit->removeElement($produit)) {
            $produit->removeRecette($this);
        }

        return $this;
    }

    /**
     * @return null|File
     */
    public function getImageFile(): ?File
    {
        return $this->image_file;
    }


    /**
     * @param null|File $image_file
     * @return Recette
     */
    public function setImageFile(?File $image_file): Recette
    {
        $this->image_file = $image_file;
        return $this;
    }
}

src/Controller/ProfilController.php
<?php


namespace App\Controller;

use App\Repository\MembreRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ObjectManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Form\EditProfilType;
use App\Entity\Membre;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class ProfilController extends AbstractController
{
    /**
     * @var MembreRepository
     */
    private $repository;

    /**
     * @param MembreRepository
     * @param EntityManagerInterface
     */
    private $em;

    public function __construct(MembreRepository $repository, EntityManagerInterface $em)
    {
        $this->repository = $repository;
        $this->em = $em;
    }
    /**
     * @Route("/profil", name="profil")
     * @return Response
     */
    public function index():Response
    {
        return $this->render('profil/view.html.twig');
    }

    /**
     * @Route("/profil/{id}/recettes", name="profil_recettes")
     * @return Response
     */
    public function showRecettes():Response {
        return $this->render('profil/recettes.html.twig');
    }
    /**
     * @Route("/profil/{id}/commandes", name="profil_commandes")
     * @return Response
     */
    public function showCommandes():Response {
        return $this->render('profil/commandes.html.twig');
    }

    /**
     * @Route("/profil/{id}/edit", name="profil_edit")
     * @param Request $request
     * @param ObjectManager $manager
     * @return RedirectResponse|Response
     * @throws Exception
     */
    public function edit(Request $request,EntityManagerInterface $manager){
        // On récupère l'utilisateur connecté
        $user = $this->getUser();
        // Création du formulaire avec validation des valeurs par défaut si inchangées
        $formEditProfil =$this->createForm(EditProfilType::class, $user,
            ['validation_groups' => ['Default']
            ]);

        //analyse de la requete passée
        $formEditProfil->handleRequest($request);
        //Vérification des données
        if ($formEditProfil->isSubmitted() && $formEditProfil->isValid()){

            $manager->persist($user);
            $manager->flush();

            return $this -> redirectToRoute('profil');
        }

        return $this-> render('profil/edit.html.twig',[
            'formProfil' => $formEditProfil->createView()
        ]);
    }

    /**
     * @Route("/profil/{id}/editpass", name="profil_edit_password")
     * @param Request $request
     * @param UserPasswordEncoderInterface $passwordEncoder
     * @return mixed
     */
    public function editPassword(Request $request, UserPasswordEncoderInterface $passwordEncoder) {
        if($request->isMethod('POST')) {
            $em = $this->getDoctrine()->getManager();
            $user = $this->getUser();

            // mots de passe identiques ?
            if($request->request->get('mdp') == $request->request->get('mdp2')){
                $user->setMdp($passwordEncoder->encodePassword($user, $request->request->get('mdp2')));
                $em->flush();
                $this->addFlash('message', 'Mot de passe mis à jour');
                return $this->redirectToRoute('profil');
            }else{
                $this->addFlash('error', 'Les deux mots de passe ne sont pas identiques.');
            }
        }
            return $this->render('profil/editPass.html.twig');
    }

}

templates/profil/commandes.html.twig
{% extends  'base.html.twig' %}

{% block title 'Commandes'%}

{% block body %}
    <div class="m-3 col-12 text-center">
        <h1>Vos commandes</h1>
    </div>

    <!-- Basic Card Example -->
    <div class="card shadow m-3">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-dark">Recettes publiées</h6>
        </div>
        <div class="card-body">


                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Date</th>
                        <th scope="col">Produits</th>
                        <th scope="col">Cout total</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for commande in app.user.commande %}
                    <tr>
                        <td> {{ commande.date|date("d/m/Y") }} </td>
                        <td>
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Produit</th>
                                        <th>Prix</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for produit in commande.produit %}
                                <tr>
                                    <td>{{ produit.nom }}</td>
                                    <td>Quantité à ajouter</td>
                                    <td>{{ produit.prix }}</td>
                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </td>
                        <td> {{ commande.coutTotal }}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>


        </div>
    </div>



{% endblock %}

templates/profil/edit.html.twig
{% extends  'base.html.twig' %}

{% block title 'Modification Profil' %}
{% block body %}
    <h1>Modification du profil</h1>
    <form method="post" enctype="multipart/form-data">
    {{ form_start(formProfil) }}
    <div class="row">
{#        <div class="col">#}
{#            {{ form_row(formProfil.imageFile,{'label':"Avatar",'attr':{'placeholder':"fichier image de xxxtaille"}}) }}#}
{#        </div>#}
        <div class="col">
            {{ form_row(formProfil.pseudo,{'label':"Nom d'utilisateur"}) }}
        </div>
    </div>
    <div class="row">
        <div class="col">
            {{ form_row(formProfil.nom,{'attr':{'placeholder':"Entrez votre nom"}}) }}
        </div>

        <div class="col">
            {{ form_row(formProfil.prenom,{'attr':{'placeholder':"Entrez votre prénomnom"}}) }}
        </div>
    </div>
    <div class="row">
        <div class="col">
            {{ form_row(formProfil.email,{'label':"E-mail"}) }}
        </div>
        <div class="col">
            {{ form_row(formProfil.tel,{'label':"N° de téléphone",'attr':{'placeholder':"Entrez votre numéro de téléphone"}}) }}
        </div>
    </div>
    {{ form_row(formProfil.adresse1,{'label':"Adresse",'attr':{'placeholder':"Entrez votre adresse"}}) }}
    {{ form_row(formProfil.adresse2,{'label':"Complément d'adresse",'attr':{'placeholder':"N° d'appartement, lotissement, etc.."}}) }}
    <div class="row">
        <div class="col">
            {{ form_row(formProfil.ville,{'attr':{'placeholder':"Entrez votre ville"}}) }}
        </div>
        <div class="col">
            {{ form_row(formProfil.cp,{'label':"Code postal",'attr':{'placeholder':"Entrez un code postal à 5 chiffres"}}) }}
        </div>
    </div>
    <button type="submit" class="btn btn-success">Enregistrer</button>
    {{ form_end(formProfil) }}
    </form>

{% endblock %}

templates/profil/editPass.html.twig
{% extends  'base.html.twig' %}

{% block title 'Profil'%}

{% block body %}
    <h1>Modifier mot de passe</h1>
    {% for message in app.flashes('error') %}
        <div class="alert alert-danger col-8">
            {{ message }}
        </div>
    {% endfor %}
    <div class="col-8">
        <form action="{{ path('profil_edit_password', {'id': app.user.id}) }}" method="post">
            <div class="form-group">
                <label for="mdp">Nouveau mot de passe</label>
                <input class="form-control" type="password" placeholder="Entrez votre mot de passe" name="mdp" id="mdp">
            </div>
            <div class="form-group">
                <label for="mdp2">Confirmation mot de passe</label>
                <input class="form-control" type="password" placeholder="Confirmer votre mot de passe" name="mdp2" id="mdp2">
            </div>
            <button class="btn btn-success" type="submit">Enregister</button>
        </form>
    </div>
{% endblock %}

templates/profil/recettes.html.twig
{% extends  'base.html.twig' %}

{% block title 'Profil'%}

{% block body %}
    <div class="m-3 col-12 text-center">
        <h1>Vos recettes</h1>
    </div>

    <!-- Basic Card Example -->
    <div class="card shadow m-3">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-dark">Recettes publiées</h6>
        </div>
        <div class="card-body">

                {% for recette in app.user.recette %}
                    <div>

                        <a href="{{ path('show_recette', {'id':recette.id}) }}">{{ recette.nom }}</a><br>


                    </div>
                {% endfor %}

        </div>
    </div>

{% endblock %}

templates/profil/view.html.twig
{% extends  'base.html.twig' %}

{% block title 'Profil' %}

{% block body %}
    {% for message in app.flashes('message') %}
        <div class="mt-4 alert alert-success col-10">{{ message }}</div>
    {% endfor %}
    <div class="card mt-3">
        <div class="card-header">
            <div class="row">
                <i class="fas fa-user-circle fa-2x ml-2 "></i>
                <p class="h4 ml-1">{{ app.user.pseudo }}</p>
            </div>
        </div>
        <div class="row no-gutters mt-2">
            <div class="col-md-auto border-right pr-1">
                {% if not app.user.photo %}
                    <img src="http://placehold.it/200x200" alt="placeholder">
                {% else %}
                    <img src="" id="img_profil" alt="image du profil">
                {% endif %}
                <div class="row ml-1">
                    <p class="ml-1 font-weight-bold">Niveau:</p>
                    {% if app.user.niveau ==1 %}
                        <p class="ml-1"> membre</p>
                    {% else %}
                        <p>placeholder</p>
                    {% endif %}
                </div>
                <div class="row ml-1">
                    <p class="ml-1 font-weight-bold">Inscription:</p>
                    <p class="ml-1">{{ app.user.inscription }}</p>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">Vos informations</h5>
                    <div class="row ml-1 border-top">
                        <p class="ml-1 font-weight-bold">Nom:</p>
                        <p class="ml-1">{{ app.user.nom }}</p>
                        <p class="ml-2 font-weight-bold">Préom:</p>
                        <p class="ml-1">{{ app.user.prenom }}</p>
                    </div>
                    <div class="row ml-1 border-top">
                        <p class="ml-1 font-weight-bold">E-mail:</p>
                        <p class="ml-1">{{ app.user.email }}</p>
                        <p class="ml-2 font-weight-bold">Téléphone:</p>
                        <p class="ml-1">{{ app.user.tel }}</p>
                    </div>
                    <div class="row border-top ">
                        <div class="col-auto">
                            <p class="font-weight-bold ml-1">Adresse 1</p>
                        </div>
                        <div class="col">{{ app.user.adresse1 }}</div>
                    </div>
                    <div class="row border-top">
                        <div class="col-auto">
                            <p class="font-weight-bold ml-1">Adresse 2</p>
                        </div>
                        <div class="col">{{ app.user.adresse2 }}</div>
                    </div>
                    <div class="row ml-1 border-top">
                        <p class="ml-1 font-weight-bold">Ville:</p>
                        <p class="ml-1">{{ app.user.ville }}</p>
                        <p class="ml-2 font-weight-bold">Code postal:</p>
                        <p class="ml-1">{{ app.user.cp }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <a href="{{ path('profil_edit', {'id': app.user.id}) }}" class="btn btn-dark mt-3 mb-3">Editer</a>

{% endblock %}